### ISSUE TITLE
ModuleNotFoundError: No module named 'sb3_contrib'

### ISSUE THREAD

**Issue by HappyDay-design** [Rik-Fox/paavi#1]
Thank you for sharing your code
My errors
Traceback (most recent call last):
  File "/home/osboxes/Desktop/paavi/main.py", line 20, in <module>
    from paavi.Agents.build import build_algo
  File "/home/osboxes/Desktop/paavi/paavi/Agents/__init__.py", line 2, in <module>
    from sb3_contrib import QRDQN, TQC
ModuleNotFoundError: No module named 'sb3_contrib'

**Comment by HappyDay-design** [comment]
`pip install sb3_contrib`
and  `python main.py`
(Py) osboxes@osboxes:~/Desktop/paavi$ /home/osboxes/anaconda3/envs/Py/bin/python /home/osboxes/Desktop/paavi/main.py
usage: single-agent-experiment [-h] [--sim-name SIM_NAME] [--headless]
                               [--seed SEED] [--sumo-port SUMO_PORT]
                               [--episodes EPISODES]
                               [--envision-port ENVISION_PORT]
                               [--algo {a2c,ddpg,dqn,ppo,her,sac,td3,qrdqn,tqc}]
                               [--env ENV] [-tb TENSORBOARD_LOG]
                               [-i TRAINED_AGENT]
                               [--truncate-last-trajectory TRUNCATE_LAST_TRAJECTORY]

**Comment by Rik-Fox** [comment]
should be `pip install sb3-contrib` from the documentation here https://sb3-contrib.readthedocs.io/en/master/index.html

Im not sure what the issue exactly is with main.py?

Also, just a warning that I won't be updating this code anytime soon, I have moved onto using a much simpler simulator I built in PyGame that is more stable and less intensive for my in person participant experiments going forward.

P.S. something is broken with the logging if you load a model to do another round of training on it; all time steps are reset as well as the learning rate and other hyper-parameters (including the replay buffer).
